# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://wm-semeru.github.io/code_lp/"

git_url = "https://github.com/wm-semeru/code_lp/tree/main/"

def custom_doc_links(name): return None
